/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sir_Chris
 */
public class allStaffDisplay extends javax.swing.JFrame {

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    public allStaffDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffList = new javax.swing.JList();
        staffNames = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LIST OF STAFF IN THE ORGANISATION");

        disp.setColumns(20);
        disp.setRows(5);
        jScrollPane1.setViewportView(disp);

        staffList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        staffList.setOpaque(false);
        staffList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffListMouseEntered(evt);
            }
        });
        staffList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                staffListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(staffList);

        staffNames.setEditable(false);
        staffNames.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        staffNames.setText("STAFF ID");
        staffNames.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(staffNames, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(staffNames, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//JUNK CALL TEST, REMEMBER TO TAKE ME OFF AS SOON AS THIOS SHIRHH GOES SOUTH
        String stmtA = "SELECT staffid FROM staffdetails";
        try{
            populateJList(staffList, stmtA, conn = mySQLconnect.connectDb());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
//THE JUNK TRIAL ENDS HERE, REMEMBER TO PILL OFF THIS SHIRH ONCE YOU DONE

        
//        String sql = "SELECT * FROM admins WHERE adminid=? and password=?";
//        
//        try{
//            pst=conn.prepareStatement(sql);
//            pst.setString(1, disp.getText());
//            //pst.setString(2, adminPass.getText());
//            rs=pst.executeQuery();
//            
//            if(rs.next()){
//                String name = rs.getString("fullname");
//                disp.setText(name);
//            //    int age = rs.getInt("staffage");
//            //    dispStaffAge.setText(""+ age);
//            //    String position = rs.getString("staffposition");
//            //    dispStaffPosition.setText(position);
//            }
//            
//        }catch(Exception ex){
//            JOptionPane.showMessageDialog(null, ex);
//        }
    }//GEN-LAST:event_formWindowOpened

    private void staffListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_staffListValueChanged
        
    }//GEN-LAST:event_staffListValueChanged

    private void staffListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffListMouseClicked
         
    }//GEN-LAST:event_staffListMouseClicked

    private void staffListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffListMouseEntered
       
    }//GEN-LAST:event_staffListMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allStaffDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allStaffDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allStaffDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allStaffDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allStaffDisplay().setVisible(true);
            }
        });
    }
    
    //TRYING OUT THIS JUNK
    public void populateJList(JList staffList, String query, Connection connection) throws SQLException
{
    DefaultListModel model = new DefaultListModel(); //create a new list model

    Statement statement = connection.createStatement();
    ResultSet resultSet = statement.executeQuery(query); //run your query

    while (resultSet.next()) //go through each row that your query returns
    {
        String itemCode = resultSet.getString("staffid"); //get the element in column "item_code"
        model.addElement(itemCode); //add each item to the model
    }
    staffList.setModel(model);

    resultSet.close();
    statement.close();

}
//OOPS JUNK ENDS HERE, REMEMBER TO TAKE THE SHIRH OFF
    
    //THIS FUNCTION IS TO ALLOW ELEMENTS SELECTED FROM THE JLIST TO UPDATE ON THE TEXTAREA
    public void specific(String stmt, String id){
        String stmt4 = "SELECT * FROM `staffdetails` WHERE `staffid`=?";
        try{
            pst=conn.prepareStatement(stmt4);
            pst.setString(1, id);
            rs=pst.executeQuery();
            
            if(rs.next()){
                String uniID = rs.getString("staffid");
                System.out.println("STAFF ID IS: " +uniID);
                String name = rs.getString("staffname");
                System.out.println("STAFF NAME IS: " +name);
                int age = rs.getInt("staffage");
                System.out.println("STAFF AGE IS: " +age);
                String position = rs.getString("staffposition");
                System.out.println("STAFF POSITION IS: " +position);
                System.out.println();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList staffList;
    private javax.swing.JTextField staffNames;
    // End of variables declaration//GEN-END:variables
}
